Add aria-label to dropdown component
curology/radiance-ui pull request #1110
Opened 2021-08-06 16:42 UTC by meron-yemane

This dropdown component was causing 'Accessibility check failed!' errors in my cypress tests. Below is a screenshot of the produced error. Simple fix was just to add an aria-label to the component. 
<img width="931" alt="Screen Shot 2021-08-06 at 9 41 32 AM" src="https://user-images.githubusercontent.com/8205569/128543752-12a321b7-7c91-492e-bb7b-f664b75896c4.png">

2021-08-06 17:23 UTC, meron-yemane commented on src/shared-components/dropdown/desktopDropdown.tsx
> +          aria-label="dropdown"
Would we want `aria-label` to refer to the dropdown as a whole or the specific options label that's currently in focus? `aria-label={currentOption ? currentOption.label : 'dropdown'}`

2021-08-06 17:53 UTC, michaeljaltamirano commented
> This dropdown component was causing 'Accessibility check failed!' errors in my cypress tests. Below is a screenshot of the produced error. Simple fix was just to add an aria-label to the component.
> <img alt="Screen Shot 2021-08-06 at 9 41 32 AM" width="931" src="https://user-images.githubusercontent.com/8205569/128543752-12a321b7-7c91-492e-bb7b-f664b75896c4.png">

Is this Cypress failure somewhere on CI (or on the Cypress dashboard) where I could take a look, or is it local dev?

2021-08-06 18:55 UTC, meron-yemane commented
> > This dropdown component was causing 'Accessibility check failed!' errors in my cypress tests. Below is a screenshot of the produced error. Simple fix was just to add an aria-label to the component.
> > <img alt="Screen Shot 2021-08-06 at 9 41 32 AM" width="931" src="https://user-images.githubusercontent.com/8205569/128543752-12a321b7-7c91-492e-bb7b-f664b75896c4.png">
> 
> Is this Cypress failure somewhere on CI (or on the Cypress dashboard) where I could take a look, or is it local dev?

The error is occurring locally. I'm pushing up the tests now so you can take a look but it seems to pass fine in CI. Interesting because the accessibility tab in Radiance for the dropdown component also points out the exact same issues I was seeing locally. Heres the [PR](https://github.com/curology/PocketDerm/pull/14014)

2021-08-06 20:44 UTC, michaeljaltamirano requested changes
I think there's room for improvement in our component definition, especially for ways to encourage happy path a11y behavior (and enforce it in our Storybook environment to prevent the issues it is reporting), but a fix for your issue can be found in userland: https://github.com/curology/PocketDerm/pull/14014/files#r684494367

2021-08-09 22:09 UTC, michaeljaltamirano commented
Closing in favor of the fix in userland mentioned above ^^^^

I've merged in https://github.com/curology/radiance-ui/pull/1117 to fix some misleading accessibility violations in our Storybook app, which includes mention of 3 new issues to fix the remaining issues, at least a couple of which are legitimate a11y issues in the library.

2021-08-09 22:09 UTC, closed without merging